security:
  storage:
    type: mysql
    local:
      private_key:
      public_key:
    database:
      group:

database:
  default:
    link:  "mysql:test:SeaMpyZXXhSpBpa7@tcp(172.18.28.240:3306)/test"