kvdb:
  database:
    endpoints:
      - 172.18.28.241:2379
      - 172.18.28.241:2380
      - 172.18.28.241:2381
registry:
  instance:
    service_name: "test-service"
    meta:
      key1: "value1"
      key2: 2
