kvdb:
  database:
    endpoints:
      - 172.18.28.240:2379
      - 172.18.28.240:2380
      - 172.18.28.240:2381
    username: "root"
    password: "qBLQveYC5ajVYNWOCT0WZAU5ent7OABC"

registry:
  instance:
    service_name: "test-service"
    meta:
      key1: "value1"
      key2: 2
