// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/junqirao/gocomponents/user/dao/internal"
)

// internalCUserTokenDao is an internal type for wrapping the internal DAO implementation.
type internalCUserTokenDao = *internal.CUserTokenDao

// cUserTokenDao is the data access object for the table c_user_token.
// You can define custom methods on it to extend its functionality as needed.
type cUserTokenDao struct {
	internalCUserTokenDao
}

var (
	// CUserToken is a globally accessible object for table c_user_token operations.
	CUserToken = cUserTokenDao{
		internal.NewCUserTokenDao(),
	}
)

// Add your custom methods and functionality below.
