// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/junqirao/gocomponents/user/dao/internal"
)

// internalCUserDao is an internal type for wrapping the internal DAO implementation.
type internalCUserDao = *internal.CUserDao

// cUserDao is the data access object for the table c_user.
// You can define custom methods on it to extend its functionality as needed.
type cUserDao struct {
	internalCUserDao
}

var (
	// CUser is a globally accessible object for table c_user operations.
	CUser = cUserDao{
		internal.NewCUserDao(),
	}
)

// Add your custom methods and functionality below.
